from fpdf import FPDF
import os
 
OUT = os.path.dirname(os.path.abspath(__file__))
 
def make_pdf(filename, title, sections):
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, title, ln=1)
    pdf.ln(4)
    for heading, body in sections:
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 10, heading, ln=1)
        pdf.set_font("Helvetica", "", 11)
        pdf.multi_cell(0, 6, body)
        pdf.ln(3)
    pdf.output(os.path.join(OUT, filename))
 
# --- PDF 1 ---
make_pdf("01_employee_handbook.pdf", "Employee Handbook - Acme Corp", [
    ("1. Introduction", "Welcome to Acme Corp. This handbook outlines the policies and procedures that govern your employment. All employees are expected to read and understand this document. Acme Corp was founded in 2005 and currently employs over 2,500 people across 12 offices worldwide."),
    ("2. Working Hours", "Standard working hours are 9:00 AM to 5:30 PM, Monday through Friday. Flexible working arrangements are available with manager approval. Core hours are 10:00 AM to 3:00 PM during which all employees must be available. Overtime must be pre-approved by your direct supervisor and is compensated at 1.5x the regular hourly rate."),
    ("3. Leave Policy", "Employees are entitled to 25 days of paid annual leave per year. Sick leave is granted up to 10 days per year with a medical certificate required for absences exceeding 3 consecutive days. Parental leave is 16 weeks for primary caregivers and 4 weeks for secondary caregivers, fully paid. Unpaid leave of up to 30 days may be requested for personal reasons."),
    ("4. Code of Conduct", "All employees must maintain professional behavior. Harassment, discrimination, and bullying are strictly prohibited. Violations will result in disciplinary action up to and including termination. Employees must declare any conflicts of interest to the Ethics Committee within 30 days of becoming aware of them."),
    ("5. Remote Work Policy", "Employees may work remotely up to 3 days per week with manager approval. A stable internet connection and a dedicated workspace are required. Remote workers must be available during core hours and attend all mandatory in-person meetings. Equipment allowance of $500 is provided annually for home office setup."),
])
 
# --- PDF 2 ---
make_pdf("02_product_specification.pdf", "Product Specification: SmartWidget X200", [
    ("1. Overview", "The SmartWidget X200 is a next-generation IoT sensor designed for industrial monitoring applications. It features real-time data collection, edge computing capabilities, and seamless cloud integration. The device operates in temperatures ranging from -40C to 85C and has an IP67 waterproof rating."),
    ("2. Technical Specifications", "Processor: ARM Cortex-M4 running at 120MHz. Memory: 256KB SRAM, 1MB Flash. Connectivity: WiFi 802.11 b/g/n, Bluetooth 5.0, LoRaWAN. Sensors: Temperature (accuracy +/-0.1C), Humidity (accuracy +/-2%), Pressure (range 300-1100 hPa), Accelerometer (3-axis, 16g range). Power: 3.7V LiPo battery, 2000mAh, typical battery life 18 months."),
    ("3. Installation Requirements", "Mount the device using the included bracket at a height of 2-3 meters. Ensure line of sight to the nearest gateway within 500 meters for LoRaWAN or 30 meters for WiFi. The device must be calibrated within 24 hours of installation using the SmartWidget Calibration App. Firmware updates are delivered over-the-air and require a minimum battery level of 30%."),
    ("4. Data Output Format", "The device transmits data in JSON format every 60 seconds (configurable from 10 seconds to 60 minutes). Each payload includes: device_id, timestamp (UTC), temperature, humidity, pressure, battery_level, and signal_strength. Data is encrypted using AES-256 before transmission. Historical data is stored on-device for up to 7 days in case of connectivity loss."),
    ("5. Warranty and Support", "The SmartWidget X200 comes with a 3-year manufacturer warranty covering hardware defects. Software support includes firmware updates for 5 years from the date of purchase. Extended warranty options are available for an additional 2 years. Technical support is available 24/7 via email at support@smartwidget.com or by phone at +1-800-555-0199."),
])
 
# --- PDF 3 ---
make_pdf("03_financial_report.pdf", "Q3 2024 Financial Report - TechGlobal Inc.", [
    ("Executive Summary", "TechGlobal Inc. reported revenue of $847 million for Q3 2024, representing a 12% year-over-year increase. Net income was $124 million, up from $98 million in Q3 2023. Operating margin improved to 18.2% from 15.7% in the prior year period. The company generated $156 million in free cash flow during the quarter."),
    ("Revenue Breakdown", "Software licensing revenue was $412 million (49% of total), up 18% YoY. Cloud services revenue was $289 million (34% of total), up 24% YoY. Professional services revenue was $146 million (17% of total), down 3% YoY. The company added 340 new enterprise customers during the quarter, bringing the total to 4,200. Annual recurring revenue (ARR) reached $1.8 billion."),
    ("Operating Expenses", "Total operating expenses were $693 million. Research and development spending was $187 million (22% of revenue), focused on AI and machine learning capabilities. Sales and marketing expenses were $298 million (35% of revenue). General and administrative costs were $208 million (25% of revenue). The company hired 450 new employees during the quarter."),
    ("Balance Sheet Highlights", "Total assets were $3.2 billion as of September 30, 2024. Cash and cash equivalents were $892 million. Total debt was $450 million with a debt-to-equity ratio of 0.28. Accounts receivable were $312 million with a DSO of 45 days. The company repurchased $75 million of its own shares during the quarter."),
    ("Outlook", "For Q4 2024, the company expects revenue between $880 million and $910 million. Full-year 2024 revenue is expected to be between $3.2 billion and $3.3 billion. The company plans to invest $200 million in AI infrastructure in 2025. Two acquisitions are under evaluation with a combined value of approximately $350 million."),
])
 
# --- PDF 4 ---
make_pdf("04_research_paper.pdf", "Machine Learning Approaches for Predictive Maintenance", [
    ("Abstract", "This paper presents a comparative study of machine learning algorithms for predictive maintenance in manufacturing environments. We evaluate Random Forest, LSTM networks, and Transformer-based models on a dataset of 50,000 sensor readings from 200 industrial machines over 24 months. Our results show that the Transformer-based approach achieves 94.2% accuracy in predicting failures 48 hours in advance, outperforming LSTM (91.7%) and Random Forest (87.3%)."),
    ("1. Introduction", "Predictive maintenance aims to predict equipment failures before they occur, reducing downtime and maintenance costs. Traditional approaches rely on scheduled maintenance intervals, which often result in either premature replacement of functional components or unexpected failures. Machine learning offers the potential to analyze sensor data patterns and predict failures with high accuracy. The global predictive maintenance market is expected to reach $23.5 billion by 2027."),
    ("2. Methodology", "We collected vibration, temperature, pressure, and acoustic data from 200 CNC machines in three manufacturing plants. Data was sampled at 1Hz for 24 months, yielding approximately 50,000 labeled data points. Features were extracted using a sliding window of 60 minutes with 50% overlap. We used 70% of the data for training, 15% for validation, and 15% for testing. All models were trained on NVIDIA A100 GPUs using PyTorch 2.0."),
    ("3. Results", "The Transformer model achieved the highest F1 score of 0.932, with precision of 0.941 and recall of 0.923. False positive rate was 3.2%, meaning only 3.2% of predicted failures did not actually occur. The model successfully predicted 92.3% of actual failures at least 48 hours in advance. Training time was 4.5 hours for the Transformer model compared to 1.2 hours for LSTM and 0.3 hours for Random Forest."),
    ("4. Discussion", "The Transformer model's superior performance is attributed to its self-attention mechanism, which captures long-range dependencies in sensor data. However, it requires significantly more computational resources for both training and inference. For resource-constrained environments, the LSTM model offers a good balance between accuracy and computational cost. Random Forest remains viable for scenarios where interpretability is prioritized over raw accuracy."),
    ("5. Conclusion", "We demonstrate that Transformer-based models achieve state-of-the-art performance for predictive maintenance. Future work will explore federated learning approaches to train models across multiple manufacturing sites without sharing raw sensor data. We also plan to investigate the use of foundation models pre-trained on industrial sensor data."),
])
 
# --- PDF 5 ---
make_pdf("05_legal_contract.pdf", "Software License Agreement", [
    ("1. Parties", "This Software License Agreement (the 'Agreement') is entered into as of January 15, 2025, by and between DataFlow Systems Inc., a Delaware corporation with offices at 100 Innovation Drive, San Jose, CA 95134 ('Licensor'), and GlobalRetail Corp., a New York corporation with offices at 500 Commerce Street, New York, NY 10001 ('Licensee')."),
    ("2. Grant of License", "Subject to the terms of this Agreement, Licensor grants Licensee a non-exclusive, non-transferable license to use the DataFlow Analytics Platform (the 'Software') for a period of 36 months. The license covers up to 500 named users and 10 concurrent API connections. Licensee may not sublicense, distribute, or make the Software available to any third party without prior written consent."),
    ("3. Fees and Payment", "Licensee shall pay an annual license fee of $450,000, payable in quarterly installments of $112,500 due on the first business day of each calendar quarter. Late payments shall accrue interest at a rate of 1.5% per month. Implementation services are billed separately at $250 per hour. Total estimated implementation cost is $180,000 for a 12-week deployment."),
    ("4. Data Protection", "Licensor shall process Licensee's data solely for the purpose of providing the Software services. All data shall be stored within the United States and encrypted at rest using AES-256 encryption. Licensor shall maintain SOC 2 Type II certification throughout the term of this Agreement. In the event of a data breach, Licensor shall notify Licensee within 72 hours of discovery."),
    ("5. Termination", "Either party may terminate this Agreement with 90 days written notice. In the event of a material breach, the non-breaching party may terminate with 30 days written notice if the breach is not cured within that period. Upon termination, Licensor shall return or destroy all Licensee data within 60 days. Licensee shall pay all fees accrued through the termination date."),
    ("6. Limitation of Liability", "In no event shall either party's total liability exceed the total fees paid or payable under this Agreement during the 12-month period preceding the claim. Neither party shall be liable for indirect, incidental, special, consequential, or punitive damages, including lost profits or lost data, regardless of the theory of liability."),
])
 
# --- PDF 6 ---
make_pdf("06_medical_guidelines.pdf", "Clinical Guidelines: Type 2 Diabetes Management", [
    ("1. Diagnosis Criteria", "Type 2 diabetes is diagnosed when fasting plasma glucose is 126 mg/dL or higher on two separate occasions, or HbA1c is 6.5% or higher, or 2-hour plasma glucose is 200 mg/dL or higher during an oral glucose tolerance test. Random plasma glucose of 200 mg/dL or higher with classic symptoms of hyperglycemia is also diagnostic. Prediabetes is defined as fasting glucose of 100-125 mg/dL or HbA1c of 5.7-6.4%."),
    ("2. First-Line Treatment", "Metformin is the recommended first-line pharmacological therapy for Type 2 diabetes. Initial dose is 500mg once daily with meals, titrated to a maximum of 2000mg daily in divided doses. Metformin reduces HbA1c by approximately 1.0-1.5%. Common side effects include gastrointestinal symptoms which typically resolve within 2-4 weeks. Metformin is contraindicated in patients with eGFR below 30 mL/min."),
    ("3. Lifestyle Modifications", "All patients should receive counseling on lifestyle modifications including: a balanced diet with 45-65% of calories from carbohydrates, 150 minutes per week of moderate-intensity aerobic exercise, weight loss target of 5-7% of body weight for overweight patients, smoking cessation, and limiting alcohol intake to no more than 1 drink per day for women and 2 for men. Medical nutrition therapy should be provided by a registered dietitian."),
    ("4. Monitoring", "HbA1c should be measured every 3 months until stable, then every 6 months. Target HbA1c is less than 7.0% for most adults, but may be individualized (less than 6.5% for younger patients, less than 8.0% for elderly or those with comorbidities). Self-monitoring of blood glucose is recommended for patients on insulin. Annual screening should include: dilated eye exam, foot exam, urine albumin-to-creatinine ratio, lipid panel, and serum creatinine."),
    ("5. Complications Management", "Cardiovascular risk should be assessed annually. Statin therapy is recommended for all diabetic patients aged 40-75. Blood pressure target is less than 130/80 mmHg. ACE inhibitors or ARBs are first-line for hypertension in diabetic patients. Diabetic nephropathy screening should begin at diagnosis and annually thereafter. Patients with peripheral neuropathy should receive foot care education and annual monofilament testing."),
])
 
# --- PDF 7 ---
make_pdf("07_project_plan.pdf", "Project Plan: E-Commerce Platform Migration", [
    ("1. Project Overview", "This project involves migrating the existing monolithic e-commerce platform to a microservices architecture on AWS. The current platform handles 2 million daily active users and processes approximately 50,000 orders per day. The migration must be completed with zero downtime and no data loss. Total project budget is $2.4 million over 18 months."),
    ("2. Phase 1: Assessment (Months 1-3)", "Conduct a thorough assessment of the existing system including: database schema analysis (PostgreSQL, 450 tables, 2.3TB), API inventory (312 endpoints), dependency mapping, and performance baseline. Deliverables include an architecture design document, risk assessment, and detailed migration plan. Team: 2 architects, 3 senior engineers, 1 DBA. Estimated cost: $380,000."),
    ("3. Phase 2: Core Services (Months 4-9)", "Build core microservices: User Service, Product Catalog, Order Management, Payment Processing, and Inventory Management. Each service will have its own database (database-per-service pattern). Inter-service communication via Apache Kafka for async events and gRPC for sync calls. API Gateway using Kong. Team: 4 backend engineers, 2 frontend engineers, 2 DevOps, 1 QA lead. Estimated cost: $920,000."),
    ("4. Phase 3: Data Migration (Months 10-13)", "Implement dual-write pattern to keep both old and new systems in sync during migration. Use AWS DMS for initial data migration and CDC (Change Data Capture) for ongoing sync. Data validation framework to compare records between old and new systems. Rollback plan: ability to switch back to monolith within 15 minutes. Team: 2 data engineers, 1 DBA, 2 backend engineers. Estimated cost: $540,000."),
    ("5. Phase 4: Cutover and Optimization (Months 14-18)", "Gradual traffic shifting using weighted routing: 10% to new system in month 14, 50% by month 15, 100% by month 16. Performance optimization and cost reduction in months 17-18. Decommission old system after 30-day observation period. Success criteria: p99 latency under 200ms, error rate below 0.1%, cost reduction of at least 30%. Team: full team. Estimated cost: $560,000."),
    ("6. Risk Register", "Key risks: (1) Data inconsistency during dual-write period - mitigation: automated reconciliation jobs running every 5 minutes. (2) Performance degradation during migration - mitigation: load testing at 3x peak traffic before each phase. (3) Team attrition - mitigation: knowledge sharing sessions and documentation requirements. (4) Budget overrun - mitigation: 15% contingency buffer ($360,000) included in total budget."),
])
 
# --- PDF 8 ---
make_pdf("08_security_policy.pdf", "Information Security Policy v3.2", [
    ("1. Purpose and Scope", "This policy establishes the information security requirements for all employees, contractors, and third-party users of CyberShield Corp's information systems. It applies to all data classified as Confidential, Internal, or Public. Compliance with this policy is mandatory and violations may result in disciplinary action, termination, or legal proceedings."),
    ("2. Access Control", "All access to information systems must follow the principle of least privilege. Multi-factor authentication (MFA) is required for all remote access and privileged accounts. Passwords must be at least 14 characters, include uppercase, lowercase, numbers, and special characters, and must be changed every 90 days. Service accounts must use certificate-based authentication. Access reviews must be conducted quarterly by system owners."),
    ("3. Data Classification", "Data is classified into three levels: (1) Confidential - customer PII, financial records, trade secrets, source code. Requires encryption at rest and in transit, access logging, and DLP controls. (2) Internal - internal communications, project documents, employee directories. Requires access controls and should not be shared externally. (3) Public - marketing materials, published reports, public website content. No special controls required."),
    ("4. Incident Response", "All security incidents must be reported to the Security Operations Center (SOC) within 1 hour of discovery via email security@cybershield.com or phone extension 5555. The incident response process follows four phases: (1) Detection and Analysis - triage within 30 minutes, (2) Containment - isolate affected systems within 2 hours, (3) Eradication and Recovery - remove threat and restore services, (4) Post-Incident Review - lessons learned within 5 business days."),
    ("5. Network Security", "All network traffic must pass through the corporate firewall. VPN is required for all remote connections using IKEv2/IPSec protocol. Network segmentation must separate production, development, and corporate environments. Intrusion detection systems (IDS) must monitor all network segments. Vulnerability scanning must be performed weekly on all internet-facing systems and monthly on internal systems."),
    ("6. Third-Party Risk", "All third-party vendors with access to company data must complete a security assessment before onboarding. Vendors handling Confidential data must maintain SOC 2 Type II or ISO 27001 certification. Vendor access must be reviewed annually and revoked within 24 hours of contract termination. Data processing agreements must be in place before any data sharing occurs."),
])
 
# --- PDF 9 ---
make_pdf("09_training_manual.pdf", "Training Manual: Customer Support Platform", [
    ("1. Getting Started", "Welcome to the HelpDesk Pro training manual. This guide will walk you through all features of our customer support platform. To log in, navigate to helpdesk.company.com and enter your employee credentials. First-time users must complete the onboarding wizard which takes approximately 15 minutes. Your default role is 'Agent' with permissions to view and respond to tickets in your assigned queue."),
    ("2. Ticket Management", "Tickets are automatically created from customer emails, chat messages, and phone calls. Each ticket has a priority level: P1 (Critical - 1 hour SLA), P2 (High - 4 hour SLA), P3 (Medium - 8 hour SLA), P4 (Low - 24 hour SLA). To assign a ticket, click the 'Assign' button and select an agent or team. Tickets can be escalated by changing the priority or reassigning to a senior agent. All ticket updates are logged in the activity timeline."),
    ("3. Knowledge Base", "The knowledge base contains 2,500 articles organized into 45 categories. To search, use the search bar at the top of the screen. You can filter by category, date, and author. When responding to a ticket, click 'Insert Article' to embed a knowledge base link in your response. Articles are rated by customers and agents. Articles with a rating below 3.0 are flagged for review. To create a new article, click 'New Article' and follow the template."),
    ("4. Reporting and Analytics", "The dashboard shows real-time metrics: open tickets, average response time, customer satisfaction score (CSAT), and agent utilization. Weekly reports are automatically generated every Monday at 8:00 AM and sent to team leads. Custom reports can be created using the Report Builder. Key metrics to track: First Response Time (target: under 2 hours), Resolution Time (target: under 24 hours), CSAT (target: above 4.2/5.0), and First Contact Resolution rate (target: above 70%)."),
    ("5. Automation Rules", "Automation rules can be configured to handle repetitive tasks. Examples: auto-assign tickets based on keywords, send acknowledgment emails within 5 minutes of ticket creation, escalate P1 tickets if not responded to within 30 minutes, close tickets automatically after 7 days of customer inactivity. To create a rule, go to Settings > Automation > New Rule. Each rule has a trigger, conditions, and actions. Rules are evaluated in priority order."),
    ("6. Integration Guide", "HelpDesk Pro integrates with: Slack (real-time notifications), Salesforce (customer data sync), Jira (bug tracking escalation), and Twilio (phone support). To configure an integration, go to Settings > Integrations and follow the setup wizard. API access is available for custom integrations. Rate limit is 1000 requests per minute per API key. API documentation is available at api.helpdeskpro.com/docs."),
])
 
# --- PDF 10 ---
make_pdf("10_environmental_report.pdf", "Annual Environmental Sustainability Report 2024", [
    ("Executive Summary", "GreenTech Manufacturing achieved a 23% reduction in carbon emissions compared to 2023, exceeding our target of 15%. Total emissions were 45,200 metric tons of CO2 equivalent, down from 58,700 metric tons in 2023. Water consumption decreased by 18% to 2.1 million cubic meters. Waste diversion rate improved to 87%, with only 13% of waste going to landfill. Renewable energy now accounts for 62% of our total energy consumption."),
    ("1. Carbon Emissions", "Scope 1 emissions (direct) were 12,300 metric tons, primarily from natural gas combustion in manufacturing processes. Scope 2 emissions (electricity) were 18,400 metric tons, reduced by 31% through the installation of 15MW of rooftop solar panels across 4 facilities. Scope 3 emissions (supply chain) were 14,500 metric tons. We have committed to achieving net-zero Scope 1 and 2 emissions by 2030 and net-zero across all scopes by 2040."),
    ("2. Water Management", "Total water withdrawal was 2.1 million cubic meters, with 78% sourced from municipal supply and 22% from rainwater harvesting. Water recycling rate was 45%, up from 32% in 2023. A new closed-loop cooling system at the Detroit plant reduced water consumption by 340,000 cubic meters annually. Zero water discharge violations were recorded during the reporting period. Target for 2025: reduce water intensity by an additional 10%."),
    ("3. Waste Reduction", "Total waste generated was 8,400 metric tons. Of this, 4,200 metric tons (50%) were recycled, 3,108 metric tons (37%) were composted or used for energy recovery, and 1,092 metric tons (13%) went to landfill. Hazardous waste was 120 metric tons, all disposed of through certified hazardous waste handlers. Single-use plastics in packaging were reduced by 65% through the adoption of biodegradable alternatives."),
    ("4. Supply Chain Sustainability", "85% of our top 100 suppliers have committed to science-based emissions targets. We conducted 45 supplier sustainability audits during 2024, with 3 suppliers placed on improvement plans. Local sourcing increased to 40% of total procurement spend, reducing transportation emissions. A new Supplier Sustainability Scorecard was introduced, evaluating suppliers on emissions, water use, waste management, and labor practices."),
    ("5. Goals for 2025", "Key targets for 2025: (1) Reduce total emissions by an additional 15% to approximately 38,400 metric tons. (2) Achieve 75% renewable energy usage. (3) Reach 90% waste diversion rate. (4) Install EV charging stations at all facilities. (5) Launch a product carbon footprint labeling program. (6) Achieve ISO 14001 certification for remaining 2 uncertified facilities. Capital investment planned: $12 million for sustainability initiatives."),
])
 
print("All 10 PDFs generated successfully.")